sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - ./.travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && ./.travis/deploy_heroku.sh
